layout_spectrum: 0.07590161985717714
typography_spectrum: 0.44955634232610464
color:
  brandStrength: 0.4875027481466532
  lightness: 0.5285870507359505
  saturation: 0.42631612182594836
  rhythmicContrast: 0.6104268892668188
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
author:
  name: Thijs van Oorschot
  email: info@thijsvanoorschot.nl
  url: www.thijsvanoorschot.nl
name: Grapheme
title: Thijs van Oorschot
description: Integrated Product Design Engineer
