typography_spectrum: 0.5874301923904568
color:
  brandStrength: 0.3620472957845777
  lightness: 0.8381609874777496
  saturation: 0.944540239404887
  rhythmicContrast: 0.18403837434016168
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.8094142267946154
author:
  name: Thijs van Oorschot
  email: info@thijsvanoorschot.nl
  url: www.thijsvanoorschot.nl
name: Grapheme
title: Thijs van Oorschot
description: Integrated Product Design Engineer
