layout_spectrum: 0.4462166177108884
typography_spectrum: 0.3466493524610996
color:
  brandStrength: 0.2072967286221683
  lightness: 0.5457872692495584
  saturation: 0.4049338512122631
  rhythmicContrast: 0.9025667526293546
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
author:
  name: Thijs van Oorschot
  email: info@thijsvanoorschot.nl
  url: www.thijsvanoorschot.nl
name: Grapheme
title: Thijs van Oorschot
description: Integrated Product Design Engineer
